name: release-build
on: [push]
jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      # check
      - name: checkout
        uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: set auth_token
        run: export SENTRY_AUTH=${{ secrets.SSH_HOST }}

      - name: build
        run: npm run build

      - name: deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./dist/*
          scp_target: /home/web/auth/
